import type { Config } from 'tailwindcss'

export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      // Colours resolve through CSS variables (see index.css) so the SAME class
      // names mean different values per theme. `bg-white`, `text-slate-900` and
      // friends appear ~1500 times across 48 files; re-pointing the palette is
      // what let dark mode land without editing any of them.
      colors: {
        // Literal on purpose. `text-white`, `border-white/10` and `ring-white`
        // sit on coloured or dark chrome that stays coloured in both themes, so
        // white has to keep meaning white. The card SURFACE is a separate token
        // below — that is the thing that must go dark.
        white: '#ffffff',
        'surface-card': 'rgb(var(--c-surface-card) / <alpha-value>)',
        slate: {
          50: 'rgb(var(--c-slate-50) / <alpha-value>)',
          100: 'rgb(var(--c-slate-100) / <alpha-value>)',
          200: 'rgb(var(--c-slate-200) / <alpha-value>)',
          300: 'rgb(var(--c-slate-300) / <alpha-value>)',
          400: 'rgb(var(--c-slate-400) / <alpha-value>)',
          500: 'rgb(var(--c-slate-500) / <alpha-value>)',
          600: 'rgb(var(--c-slate-600) / <alpha-value>)',
          700: 'rgb(var(--c-slate-700) / <alpha-value>)',
          800: 'rgb(var(--c-slate-800) / <alpha-value>)',
          900: 'rgb(var(--c-slate-900) / <alpha-value>)',
          950: 'rgb(var(--c-slate-950) / <alpha-value>)',
        },
        rose: {
          50: 'rgb(var(--c-rose-50) / <alpha-value>)',
          100: 'rgb(var(--c-rose-100) / <alpha-value>)',
          200: 'rgb(var(--c-rose-200) / <alpha-value>)',
          300: 'rgb(var(--c-rose-300) / <alpha-value>)',
          400: 'rgb(var(--c-rose-400) / <alpha-value>)',
          500: 'rgb(var(--c-rose-500) / <alpha-value>)',
          600: 'rgb(var(--c-rose-600) / <alpha-value>)',
          700: 'rgb(var(--c-rose-700) / <alpha-value>)',
          800: 'rgb(var(--c-rose-800) / <alpha-value>)',
          900: 'rgb(var(--c-rose-900) / <alpha-value>)',
          950: 'rgb(var(--c-rose-950) / <alpha-value>)',
        },
        amber: {
          50: 'rgb(var(--c-amber-50) / <alpha-value>)',
          100: 'rgb(var(--c-amber-100) / <alpha-value>)',
          200: 'rgb(var(--c-amber-200) / <alpha-value>)',
          300: 'rgb(var(--c-amber-300) / <alpha-value>)',
          400: 'rgb(var(--c-amber-400) / <alpha-value>)',
          500: 'rgb(var(--c-amber-500) / <alpha-value>)',
          600: 'rgb(var(--c-amber-600) / <alpha-value>)',
          700: 'rgb(var(--c-amber-700) / <alpha-value>)',
          800: 'rgb(var(--c-amber-800) / <alpha-value>)',
          900: 'rgb(var(--c-amber-900) / <alpha-value>)',
          950: 'rgb(var(--c-amber-950) / <alpha-value>)',
        },
        emerald: {
          50: 'rgb(var(--c-emerald-50) / <alpha-value>)',
          100: 'rgb(var(--c-emerald-100) / <alpha-value>)',
          200: 'rgb(var(--c-emerald-200) / <alpha-value>)',
          300: 'rgb(var(--c-emerald-300) / <alpha-value>)',
          400: 'rgb(var(--c-emerald-400) / <alpha-value>)',
          500: 'rgb(var(--c-emerald-500) / <alpha-value>)',
          600: 'rgb(var(--c-emerald-600) / <alpha-value>)',
          700: 'rgb(var(--c-emerald-700) / <alpha-value>)',
          800: 'rgb(var(--c-emerald-800) / <alpha-value>)',
          900: 'rgb(var(--c-emerald-900) / <alpha-value>)',
          950: 'rgb(var(--c-emerald-950) / <alpha-value>)',
        },
        indigo: {
          50: 'rgb(var(--c-indigo-50) / <alpha-value>)',
          100: 'rgb(var(--c-indigo-100) / <alpha-value>)',
          200: 'rgb(var(--c-indigo-200) / <alpha-value>)',
          300: 'rgb(var(--c-indigo-300) / <alpha-value>)',
          400: 'rgb(var(--c-indigo-400) / <alpha-value>)',
          500: 'rgb(var(--c-indigo-500) / <alpha-value>)',
          600: 'rgb(var(--c-indigo-600) / <alpha-value>)',
          700: 'rgb(var(--c-indigo-700) / <alpha-value>)',
          800: 'rgb(var(--c-indigo-800) / <alpha-value>)',
          900: 'rgb(var(--c-indigo-900) / <alpha-value>)',
          950: 'rgb(var(--c-indigo-950) / <alpha-value>)',
        },
        sky: {
          50: 'rgb(var(--c-sky-50) / <alpha-value>)',
          100: 'rgb(var(--c-sky-100) / <alpha-value>)',
          200: 'rgb(var(--c-sky-200) / <alpha-value>)',
          300: 'rgb(var(--c-sky-300) / <alpha-value>)',
          400: 'rgb(var(--c-sky-400) / <alpha-value>)',
          500: 'rgb(var(--c-sky-500) / <alpha-value>)',
          600: 'rgb(var(--c-sky-600) / <alpha-value>)',
          700: 'rgb(var(--c-sky-700) / <alpha-value>)',
          800: 'rgb(var(--c-sky-800) / <alpha-value>)',
          900: 'rgb(var(--c-sky-900) / <alpha-value>)',
          950: 'rgb(var(--c-sky-950) / <alpha-value>)',
        },
        blue: {
          50: 'rgb(var(--c-blue-50) / <alpha-value>)',
          100: 'rgb(var(--c-blue-100) / <alpha-value>)',
          200: 'rgb(var(--c-blue-200) / <alpha-value>)',
          300: 'rgb(var(--c-blue-300) / <alpha-value>)',
          400: 'rgb(var(--c-blue-400) / <alpha-value>)',
          500: 'rgb(var(--c-blue-500) / <alpha-value>)',
          600: 'rgb(var(--c-blue-600) / <alpha-value>)',
          700: 'rgb(var(--c-blue-700) / <alpha-value>)',
          800: 'rgb(var(--c-blue-800) / <alpha-value>)',
          900: 'rgb(var(--c-blue-900) / <alpha-value>)',
          950: 'rgb(var(--c-blue-950) / <alpha-value>)',
        },
        orange: {
          50: 'rgb(var(--c-orange-50) / <alpha-value>)',
          100: 'rgb(var(--c-orange-100) / <alpha-value>)',
          200: 'rgb(var(--c-orange-200) / <alpha-value>)',
          300: 'rgb(var(--c-orange-300) / <alpha-value>)',
          400: 'rgb(var(--c-orange-400) / <alpha-value>)',
          500: 'rgb(var(--c-orange-500) / <alpha-value>)',
          600: 'rgb(var(--c-orange-600) / <alpha-value>)',
          700: 'rgb(var(--c-orange-700) / <alpha-value>)',
          800: 'rgb(var(--c-orange-800) / <alpha-value>)',
          900: 'rgb(var(--c-orange-900) / <alpha-value>)',
          950: 'rgb(var(--c-orange-950) / <alpha-value>)',
        },
        pink: {
          50: 'rgb(var(--c-pink-50) / <alpha-value>)',
          100: 'rgb(var(--c-pink-100) / <alpha-value>)',
          200: 'rgb(var(--c-pink-200) / <alpha-value>)',
          300: 'rgb(var(--c-pink-300) / <alpha-value>)',
          400: 'rgb(var(--c-pink-400) / <alpha-value>)',
          500: 'rgb(var(--c-pink-500) / <alpha-value>)',
          600: 'rgb(var(--c-pink-600) / <alpha-value>)',
          700: 'rgb(var(--c-pink-700) / <alpha-value>)',
          800: 'rgb(var(--c-pink-800) / <alpha-value>)',
          900: 'rgb(var(--c-pink-900) / <alpha-value>)',
          950: 'rgb(var(--c-pink-950) / <alpha-value>)',
        },
        violet: {
          50: 'rgb(var(--c-violet-50) / <alpha-value>)',
          100: 'rgb(var(--c-violet-100) / <alpha-value>)',
          200: 'rgb(var(--c-violet-200) / <alpha-value>)',
          300: 'rgb(var(--c-violet-300) / <alpha-value>)',
          400: 'rgb(var(--c-violet-400) / <alpha-value>)',
          500: 'rgb(var(--c-violet-500) / <alpha-value>)',
          600: 'rgb(var(--c-violet-600) / <alpha-value>)',
          700: 'rgb(var(--c-violet-700) / <alpha-value>)',
          800: 'rgb(var(--c-violet-800) / <alpha-value>)',
          900: 'rgb(var(--c-violet-900) / <alpha-value>)',
          950: 'rgb(var(--c-violet-950) / <alpha-value>)',
        },
        red: {
          50: 'rgb(var(--c-red-50) / <alpha-value>)',
          100: 'rgb(var(--c-red-100) / <alpha-value>)',
          200: 'rgb(var(--c-red-200) / <alpha-value>)',
          300: 'rgb(var(--c-red-300) / <alpha-value>)',
          400: 'rgb(var(--c-red-400) / <alpha-value>)',
          500: 'rgb(var(--c-red-500) / <alpha-value>)',
          600: 'rgb(var(--c-red-600) / <alpha-value>)',
          700: 'rgb(var(--c-red-700) / <alpha-value>)',
          800: 'rgb(var(--c-red-800) / <alpha-value>)',
          900: 'rgb(var(--c-red-900) / <alpha-value>)',
          950: 'rgb(var(--c-red-950) / <alpha-value>)',
        },
        'qira-pistachio': 'rgb(var(--c-qira-pistachio) / <alpha-value>)',
        'qira-pistachio-dk': 'rgb(var(--c-qira-pistachio-dk) / <alpha-value>)',
        'qira-pistachio-lt': 'rgb(var(--c-qira-pistachio-lt) / <alpha-value>)',
        'qira-cream': 'rgb(var(--c-qira-cream) / <alpha-value>)',
        'qira-silver': 'rgb(var(--c-qira-silver) / <alpha-value>)',
        'qira-anthracite': 'rgb(var(--c-qira-anthracite) / <alpha-value>)',
        'qira-graphite': 'rgb(var(--c-qira-graphite) / <alpha-value>)',
        'text-primary': 'rgb(var(--c-text-primary) / <alpha-value>)',
        'text-secondary': 'rgb(var(--c-text-secondary) / <alpha-value>)',
        'surface-board': 'rgb(var(--c-surface-board) / <alpha-value>)',
        'surface-sidebar': 'rgb(var(--c-surface-sidebar) / <alpha-value>)',
        'border-default': 'rgb(var(--c-border-default) / <alpha-value>)',
        // Kept literal: pre-Qira branding, not part of the themed surface.
        'jira-blue':       '#0C66E4',
        'jira-blue-dk':    '#0055CC',
        'jira-blue-lt':    '#E9F2FF',
        'status-todo':     '#DFE1E6',
        'status-ip':       '#6B9E6B',
        'status-done':     '#22A06B',
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
      },
      borderRadius: {
        card: '3px',
        btn:  '4px',
      },
      boxShadow: {
        card:        '0 1px 2px rgba(9,30,66,0.15)',
        'card-hover':'0 2px 8px rgba(9,30,66,0.20)',
        drawer:      '-4px 0 16px rgba(9,30,66,0.12)',
      },
    },
  },
  plugins: [],
} satisfies Config
